import type { Metadata } from "next";
import { Patrick_Hand, Patrick_Hand_SC, Quicksand } from "next/font/google";
import "./globals.css";

const patrickHand = Patrick_Hand({
  variable: "--font-patrick-hand",
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

const patrickHandSC = Patrick_Hand_SC({
  variable: "--font-patrick-hand-sc",
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${patrickHand.variable} ${patrickHandSC.variable} ${quicksand.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
