import type React from "react"
import type { Metadata } from "next"
import { Quicksand, Patrick_Hand, Patrick_Hand_SC } from "next/font/google"
import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const quicksand = Quicksand({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
})

const patrickHand = Patrick_Hand({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--font-hand",
})

const patrickHandSC = Patrick_Hand_SC({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--font-hand-sc",
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${patrickHand.variable} ${patrickHandSC.variable} antialiased`}>
      <body className={quicksand.className}>{children}</body>
    </html>
  )
}
